/*
 * Sajari API
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sajari.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * BatchCreateSchemaFieldsRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class BatchCreateSchemaFieldsRequest {
    public static final String SERIALIZED_NAME_FIELDS = "fields";
    @SerializedName(SERIALIZED_NAME_FIELDS)
    private java.util.List<SchemaField> fields = new java.util.ArrayList<>();


    public BatchCreateSchemaFieldsRequest fields(java.util.List<SchemaField> fields) {

        this.fields = fields;
        return this;
    }

    public BatchCreateSchemaFieldsRequest addFieldsItem(SchemaField fieldsItem) {
        this.fields.add(fieldsItem);
        return this;
    }

    /**
     * A list of fields to create.  A maximum of 1000 fields can be created in a batch.
     *
     * @return fields
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "A list of fields to create.  A maximum of 1000 fields can be created in a batch.")

    public java.util.List<SchemaField> getFields() {
        return fields;
    }


    public void setFields(java.util.List<SchemaField> fields) {
        this.fields = fields;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BatchCreateSchemaFieldsRequest batchCreateSchemaFieldsRequest = (BatchCreateSchemaFieldsRequest) o;
        return Objects.equals(this.fields, batchCreateSchemaFieldsRequest.fields);
    }

    @Override
    public int hashCode() {
        return Objects.hash(fields);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class BatchCreateSchemaFieldsRequest {\n");
        sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

