/*
 * Search.io API
 * Search.io offers a search and discovery service with Neuralsearch®, the world's first instant AI search technology. Businesses of all sizes use Search.io to build site search and discovery solutions that maximize e-commerce revenue, optimize on-site customer experience, and scale their online presence.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@search.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sajari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sajari.client.model.BatchUpsertRecordsRequestPipeline;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BatchUpsertRecordsRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class BatchUpsertRecordsRequest {
  public static final String SERIALIZED_NAME_PIPELINE = "pipeline";
  @SerializedName(SERIALIZED_NAME_PIPELINE)
  private BatchUpsertRecordsRequestPipeline pipeline;

  public static final String SERIALIZED_NAME_RECORDS = "records";
  @SerializedName(SERIALIZED_NAME_RECORDS)
  private java.util.List<Object> records = new java.util.ArrayList<>();

  public static final String SERIALIZED_NAME_VARIABLES = "variables";
  @SerializedName(SERIALIZED_NAME_VARIABLES)
  private java.util.Map<String, Object> variables = null;

  public BatchUpsertRecordsRequest() { 
  }

  public BatchUpsertRecordsRequest pipeline(BatchUpsertRecordsRequestPipeline pipeline) {
    
    this.pipeline = pipeline;
    return this;
  }

   /**
   * Get pipeline
   * @return pipeline
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BatchUpsertRecordsRequestPipeline getPipeline() {
    return pipeline;
  }


  public void setPipeline(BatchUpsertRecordsRequestPipeline pipeline) {
    this.pipeline = pipeline;
  }


  public BatchUpsertRecordsRequest records(java.util.List<Object> records) {
    
    this.records = records;
    return this;
  }

  public BatchUpsertRecordsRequest addRecordsItem(Object recordsItem) {
    this.records.add(recordsItem);
    return this;
  }

   /**
   * A list of records to upsert.  A maximum of 200 records can be upsert in a batch.
   * @return records
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "A list of records to upsert.  A maximum of 200 records can be upsert in a batch.")

  public java.util.List<Object> getRecords() {
    return records;
  }


  public void setRecords(java.util.List<Object> records) {
    this.records = records;
  }


  public BatchUpsertRecordsRequest variables(java.util.Map<String, Object> variables) {
    
    this.variables = variables;
    return this;
  }

  public BatchUpsertRecordsRequest putVariablesItem(String key, Object variablesItem) {
    if (this.variables == null) {
      this.variables = new java.util.HashMap<>();
    }
    this.variables.put(key, variablesItem);
    return this;
  }

   /**
   * The initial values for the variables the pipeline operates on and transforms throughout its steps.
   * @return variables
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The initial values for the variables the pipeline operates on and transforms throughout its steps.")

  public java.util.Map<String, Object> getVariables() {
    return variables;
  }


  public void setVariables(java.util.Map<String, Object> variables) {
    this.variables = variables;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchUpsertRecordsRequest batchUpsertRecordsRequest = (BatchUpsertRecordsRequest) o;
    return Objects.equals(this.pipeline, batchUpsertRecordsRequest.pipeline) &&
        Objects.equals(this.records, batchUpsertRecordsRequest.records) &&
        Objects.equals(this.variables, batchUpsertRecordsRequest.variables);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pipeline, records, variables);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchUpsertRecordsRequest {\n");
    sb.append("    pipeline: ").append(toIndentedString(pipeline)).append("\n");
    sb.append("    records: ").append(toIndentedString(records)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

