/*
 * Search.io API
 * Search.io offers a search and discovery service with Neuralsearch®, the world's first instant AI search technology. Businesses of all sizes use Search.io to build site search and discovery solutions that maximize e-commerce revenue, optimize on-site customer experience, and scale their online presence.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@search.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sajari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sajari.client.model.BatchUpdateRecordsResponseError;
import com.sajari.client.model.BatchUpdateRecordsResponseRecord;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BatchUpdateRecordsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class BatchUpdateRecordsResponse {
  public static final String SERIALIZED_NAME_ERRORS = "errors";
  @SerializedName(SERIALIZED_NAME_ERRORS)
  private java.util.List<BatchUpdateRecordsResponseError> errors = null;

  public static final String SERIALIZED_NAME_RECORDS = "records";
  @SerializedName(SERIALIZED_NAME_RECORDS)
  private java.util.List<BatchUpdateRecordsResponseRecord> records = null;

  public BatchUpdateRecordsResponse() { 
  }

  public BatchUpdateRecordsResponse errors(java.util.List<BatchUpdateRecordsResponseError> errors) {
    
    this.errors = errors;
    return this;
  }

  public BatchUpdateRecordsResponse addErrorsItem(BatchUpdateRecordsResponseError errorsItem) {
    if (this.errors == null) {
      this.errors = new java.util.ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * The errors that occurred.
   * @return errors
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The errors that occurred.")

  public java.util.List<BatchUpdateRecordsResponseError> getErrors() {
    return errors;
  }


  public void setErrors(java.util.List<BatchUpdateRecordsResponseError> errors) {
    this.errors = errors;
  }


  public BatchUpdateRecordsResponse records(java.util.List<BatchUpdateRecordsResponseRecord> records) {
    
    this.records = records;
    return this;
  }

  public BatchUpdateRecordsResponse addRecordsItem(BatchUpdateRecordsResponseRecord recordsItem) {
    if (this.records == null) {
      this.records = new java.util.ArrayList<>();
    }
    this.records.add(recordsItem);
    return this;
  }

   /**
   * A list of updated records.
   * @return records
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of updated records.")

  public java.util.List<BatchUpdateRecordsResponseRecord> getRecords() {
    return records;
  }


  public void setRecords(java.util.List<BatchUpdateRecordsResponseRecord> records) {
    this.records = records;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchUpdateRecordsResponse batchUpdateRecordsResponse = (BatchUpdateRecordsResponse) o;
    return Objects.equals(this.errors, batchUpdateRecordsResponse.errors) &&
        Objects.equals(this.records, batchUpdateRecordsResponse.records);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errors, records);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchUpdateRecordsResponse {\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    records: ").append(toIndentedString(records)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

