/*
 * Search.io API
 * Search.io offers a search and discovery service with Neuralsearch®, the world's first instant AI search technology. Businesses of all sizes use Search.io to build site search and discovery solutions that maximize e-commerce revenue, optimize on-site customer experience, and scale their online presence.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@search.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sajari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BatchUpsertRecordsResponseVariables
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class BatchUpsertRecordsResponseVariables {
  public static final String SERIALIZED_NAME_INDEX = "index";
  @SerializedName(SERIALIZED_NAME_INDEX)
  private Integer index;

  public static final String SERIALIZED_NAME_VARIABLES = "variables";
  @SerializedName(SERIALIZED_NAME_VARIABLES)
  private java.util.Map<String, Object> variables = null;

  public BatchUpsertRecordsResponseVariables() { 
  }

  public BatchUpsertRecordsResponseVariables index(Integer index) {
    
    this.index = index;
    return this;
  }

   /**
   * Index of the record in &#x60;records&#x60; that these variables correspond to.
   * @return index
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Index of the record in `records` that these variables correspond to.")

  public Integer getIndex() {
    return index;
  }


  public void setIndex(Integer index) {
    this.index = index;
  }


  public BatchUpsertRecordsResponseVariables variables(java.util.Map<String, Object> variables) {
    
    this.variables = variables;
    return this;
  }

  public BatchUpsertRecordsResponseVariables putVariablesItem(String key, Object variablesItem) {
    if (this.variables == null) {
      this.variables = new java.util.HashMap<>();
    }
    this.variables.put(key, variablesItem);
    return this;
  }

   /**
   * The variables.
   * @return variables
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The variables.")

  public java.util.Map<String, Object> getVariables() {
    return variables;
  }


  public void setVariables(java.util.Map<String, Object> variables) {
    this.variables = variables;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchUpsertRecordsResponseVariables batchUpsertRecordsResponseVariables = (BatchUpsertRecordsResponseVariables) o;
    return Objects.equals(this.index, batchUpsertRecordsResponseVariables.index) &&
        Objects.equals(this.variables, batchUpsertRecordsResponseVariables.variables);
  }

  @Override
  public int hashCode() {
    return Objects.hash(index, variables);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchUpsertRecordsResponseVariables {\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

