/*
 * Sajari API
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sajari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BatchUpsertRecordsResponseVariables
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-08-19T12:37:05.253753Z[Etc/UTC]")
public class BatchUpsertRecordsResponseVariables {
  public static final String SERIALIZED_NAME_INDEX = "index";
  @SerializedName(SERIALIZED_NAME_INDEX)
  private Integer index;

  public static final String SERIALIZED_NAME_VARIABLES = "variables";
  @SerializedName(SERIALIZED_NAME_VARIABLES)
  private Object variables;


  public BatchUpsertRecordsResponseVariables index(Integer index) {
    
    this.index = index;
    return this;
  }

   /**
   * Index of the record in &#x60;records&#x60; that these variables correspond to.
   * @return index
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Index of the record in `records` that these variables correspond to.")

  public Integer getIndex() {
    return index;
  }


  public void setIndex(Integer index) {
    this.index = index;
  }


  public BatchUpsertRecordsResponseVariables variables(Object variables) {
    
    this.variables = variables;
    return this;
  }

   /**
   * The variables.
   * @return variables
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The variables.")

  public Object getVariables() {
    return variables;
  }


  public void setVariables(Object variables) {
    this.variables = variables;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchUpsertRecordsResponseVariables batchUpsertRecordsResponseVariables = (BatchUpsertRecordsResponseVariables) o;
    return Objects.equals(this.index, batchUpsertRecordsResponseVariables.index) &&
        Objects.equals(this.variables, batchUpsertRecordsResponseVariables.variables);
  }

  @Override
  public int hashCode() {
    return Objects.hash(index, variables);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchUpsertRecordsResponseVariables {\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

