/*
 * Search.io API
 * Search.io offers a search and discovery service with Neuralsearch®, the world's first instant AI search technology. Businesses of all sizes use Search.io to build site search and discovery solutions that maximize e-commerce revenue, optimize on-site customer experience, and scale their online presence.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@search.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sajari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sajari.client.model.ExperimentRequestPipeline;
import com.sajari.client.model.Pipeline;
import com.sajari.client.model.Promotion;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A request to perform a query experiment on a collection using a pipeline.
 */
@ApiModel(description = "A request to perform a query experiment on a collection using a pipeline.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ExperimentRequest {
  public static final String SERIALIZED_NAME_CUSTOM_PIPELINE = "custom_pipeline";
  @SerializedName(SERIALIZED_NAME_CUSTOM_PIPELINE)
  private Pipeline customPipeline;

  public static final String SERIALIZED_NAME_PIPELINE = "pipeline";
  @SerializedName(SERIALIZED_NAME_PIPELINE)
  private ExperimentRequestPipeline pipeline;

  public static final String SERIALIZED_NAME_PROMOTIONS = "promotions";
  @SerializedName(SERIALIZED_NAME_PROMOTIONS)
  private java.util.List<Promotion> promotions = null;

  public static final String SERIALIZED_NAME_VARIABLES = "variables";
  @SerializedName(SERIALIZED_NAME_VARIABLES)
  private java.util.Map<String, Object> variables = new java.util.HashMap<>();

  public ExperimentRequest() { 
  }

  public ExperimentRequest customPipeline(Pipeline customPipeline) {
    
    this.customPipeline = customPipeline;
    return this;
  }

   /**
   * Get customPipeline
   * @return customPipeline
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Pipeline getCustomPipeline() {
    return customPipeline;
  }


  public void setCustomPipeline(Pipeline customPipeline) {
    this.customPipeline = customPipeline;
  }


  public ExperimentRequest pipeline(ExperimentRequestPipeline pipeline) {
    
    this.pipeline = pipeline;
    return this;
  }

   /**
   * Get pipeline
   * @return pipeline
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ExperimentRequestPipeline getPipeline() {
    return pipeline;
  }


  public void setPipeline(ExperimentRequestPipeline pipeline) {
    this.pipeline = pipeline;
  }


  public ExperimentRequest promotions(java.util.List<Promotion> promotions) {
    
    this.promotions = promotions;
    return this;
  }

  public ExperimentRequest addPromotionsItem(Promotion promotionsItem) {
    if (this.promotions == null) {
      this.promotions = new java.util.ArrayList<>();
    }
    this.promotions.add(promotionsItem);
    return this;
  }

   /**
   * The promotions to consider active when running the search.  Provided promotions override existing promotions with the same ID.
   * @return promotions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The promotions to consider active when running the search.  Provided promotions override existing promotions with the same ID.")

  public java.util.List<Promotion> getPromotions() {
    return promotions;
  }


  public void setPromotions(java.util.List<Promotion> promotions) {
    this.promotions = promotions;
  }


  public ExperimentRequest variables(java.util.Map<String, Object> variables) {
    
    this.variables = variables;
    return this;
  }

  public ExperimentRequest putVariablesItem(String key, Object variablesItem) {
    this.variables.put(key, variablesItem);
    return this;
  }

   /**
   * The initial values for the variables the pipeline operates on and transforms throughout its steps.  The most important variable is &#x60;q&#x60; which is the query the user entered, for example:  &#x60;&#x60;&#x60;json { \&quot;q\&quot;: \&quot;search terms\&quot; } &#x60;&#x60;&#x60;  To paginate through results, set the variables &#x60;page&#x60; and &#x60;resultsPerPage&#x60;, for example:  &#x60;&#x60;&#x60;json { \&quot;q\&quot;: \&quot;search terms\&quot;, \&quot;page\&quot;: 5, \&quot;resultsPerPage\&quot;: 20 } &#x60;&#x60;&#x60;  To sort results, set the variable &#x60;sort&#x60; to the name of one of your collection&#39;s schema fields, for example:  &#x60;&#x60;&#x60;json { \&quot;q\&quot;: \&quot;search terms\&quot;, \&quot;sort\&quot;: \&quot;name\&quot; } &#x60;&#x60;&#x60;  To sort in reverse, prefix the schema field with a minus sign &#x60;-&#x60;, for example:  &#x60;&#x60;&#x60;json { \&quot;q\&quot;: \&quot;search terms\&quot;, \&quot;sort\&quot;: \&quot;-name\&quot; } &#x60;&#x60;&#x60;
   * @return variables
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The initial values for the variables the pipeline operates on and transforms throughout its steps.  The most important variable is `q` which is the query the user entered, for example:  ```json { \"q\": \"search terms\" } ```  To paginate through results, set the variables `page` and `resultsPerPage`, for example:  ```json { \"q\": \"search terms\", \"page\": 5, \"resultsPerPage\": 20 } ```  To sort results, set the variable `sort` to the name of one of your collection's schema fields, for example:  ```json { \"q\": \"search terms\", \"sort\": \"name\" } ```  To sort in reverse, prefix the schema field with a minus sign `-`, for example:  ```json { \"q\": \"search terms\", \"sort\": \"-name\" } ```")

  public java.util.Map<String, Object> getVariables() {
    return variables;
  }


  public void setVariables(java.util.Map<String, Object> variables) {
    this.variables = variables;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExperimentRequest experimentRequest = (ExperimentRequest) o;
    return Objects.equals(this.customPipeline, experimentRequest.customPipeline) &&
        Objects.equals(this.pipeline, experimentRequest.pipeline) &&
        Objects.equals(this.promotions, experimentRequest.promotions) &&
        Objects.equals(this.variables, experimentRequest.variables);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customPipeline, pipeline, promotions, variables);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExperimentRequest {\n");
    sb.append("    customPipeline: ").append(toIndentedString(customPipeline)).append("\n");
    sb.append("    pipeline: ").append(toIndentedString(pipeline)).append("\n");
    sb.append("    promotions: ").append(toIndentedString(promotions)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

