/*
 * Search.io API
 * Search.io offers a search and discovery service with Neuralsearch®, the world's first instant AI search technology. Businesses of all sizes use Search.io to build site search and discovery solutions that maximize e-commerce revenue, optimize on-site customer experience, and scale their online presence.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@search.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sajari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GeneratePipelinesRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GeneratePipelinesRequest {
  public static final String SERIALIZED_NAME_QUERY_TRAINING_FIELDS = "query_training_fields";
  @SerializedName(SERIALIZED_NAME_QUERY_TRAINING_FIELDS)
  private java.util.List<String> queryTrainingFields = null;

  public static final String SERIALIZED_NAME_SEARCHABLE_FIELDS = "searchable_fields";
  @SerializedName(SERIALIZED_NAME_SEARCHABLE_FIELDS)
  private java.util.List<String> searchableFields = new java.util.ArrayList<>();

  public GeneratePipelinesRequest() { 
  }

  public GeneratePipelinesRequest queryTrainingFields(java.util.List<String> queryTrainingFields) {
    
    this.queryTrainingFields = queryTrainingFields;
    return this;
  }

  public GeneratePipelinesRequest addQueryTrainingFieldsItem(String queryTrainingFieldsItem) {
    if (this.queryTrainingFields == null) {
      this.queryTrainingFields = new java.util.ArrayList<>();
    }
    this.queryTrainingFields.add(queryTrainingFieldsItem);
    return this;
  }

   /**
   * A list of fields to train query suggestions from.
   * @return queryTrainingFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of fields to train query suggestions from.")

  public java.util.List<String> getQueryTrainingFields() {
    return queryTrainingFields;
  }


  public void setQueryTrainingFields(java.util.List<String> queryTrainingFields) {
    this.queryTrainingFields = queryTrainingFields;
  }


  public GeneratePipelinesRequest searchableFields(java.util.List<String> searchableFields) {
    
    this.searchableFields = searchableFields;
    return this;
  }

  public GeneratePipelinesRequest addSearchableFieldsItem(String searchableFieldsItem) {
    this.searchableFields.add(searchableFieldsItem);
    return this;
  }

   /**
   * A prioritized list of fields to search.
   * @return searchableFields
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "A prioritized list of fields to search.")

  public java.util.List<String> getSearchableFields() {
    return searchableFields;
  }


  public void setSearchableFields(java.util.List<String> searchableFields) {
    this.searchableFields = searchableFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeneratePipelinesRequest generatePipelinesRequest = (GeneratePipelinesRequest) o;
    return Objects.equals(this.queryTrainingFields, generatePipelinesRequest.queryTrainingFields) &&
        Objects.equals(this.searchableFields, generatePipelinesRequest.searchableFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(queryTrainingFields, searchableFields);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeneratePipelinesRequest {\n");
    sb.append("    queryTrainingFields: ").append(toIndentedString(queryTrainingFields)).append("\n");
    sb.append("    searchableFields: ").append(toIndentedString(searchableFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

