/*
 * Search.io API
 * Search.io offers a search and discovery service with Neuralsearch®, the world's first instant AI search technology. Businesses of all sizes use Search.io to build site search and discovery solutions that maximize e-commerce revenue, optimize on-site customer experience, and scale their online presence.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@search.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sajari.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  - TYPE_UNSPECIFIED: Pipeline type not specified.  - RECORD: Record pipeline.  - QUERY: Query pipeline.
 */
@JsonAdapter(PipelineType.Adapter.class)
public enum PipelineType {
  
  TYPE_UNSPECIFIED("TYPE_UNSPECIFIED"),
  
  RECORD("RECORD"),
  
  QUERY("QUERY");

  private String value;

  PipelineType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PipelineType fromValue(String value) {
    for (PipelineType b : PipelineType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PipelineType> {
    @Override
    public void write(final JsonWriter jsonWriter, final PipelineType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PipelineType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PipelineType.fromValue(value);
    }
  }
}

