/*
 * Sajari API
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sajari.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * QueryAggregateResultDate
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class QueryAggregateResultDate {
    public static final String SERIALIZED_NAME_DATES = "dates";
    @SerializedName(SERIALIZED_NAME_DATES)
    private java.util.Map<String, Integer> dates = null;


    public QueryAggregateResultDate dates(java.util.Map<String, Integer> dates) {

        this.dates = dates;
        return this;
    }

    public QueryAggregateResultDate putDatesItem(String key, Integer datesItem) {
        if (this.dates == null) {
            this.dates = new java.util.HashMap<>();
        }
        this.dates.put(key, datesItem);
        return this;
    }

    /**
     * Get dates
     *
     * @return dates
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public java.util.Map<String, Integer> getDates() {
        return dates;
    }


    public void setDates(java.util.Map<String, Integer> dates) {
        this.dates = dates;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        QueryAggregateResultDate queryAggregateResultDate = (QueryAggregateResultDate) o;
        return Objects.equals(this.dates, queryAggregateResultDate.dates);
    }

    @Override
    public int hashCode() {
        return Objects.hash(dates);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class QueryAggregateResultDate {\n");
        sb.append("    dates: ").append(toIndentedString(dates)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

