/*
 * Search.io API
 * Search.io offers a search and discovery service with Neuralsearch®, the world's first instant AI search technology. Businesses of all sizes use Search.io to build site search and discovery solutions that maximize e-commerce revenue, optimize on-site customer experience, and scale their online presence.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@search.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sajari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sajari.client.model.QueryAggregateResultBucketsBucket;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Buckets is a full set of buckets computed in an aggregation.
 */
@ApiModel(description = "Buckets is a full set of buckets computed in an aggregation.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class QueryAggregateResultBuckets {
  public static final String SERIALIZED_NAME_BUCKETS = "buckets";
  @SerializedName(SERIALIZED_NAME_BUCKETS)
  private java.util.Map<String, QueryAggregateResultBucketsBucket> buckets = null;

  public QueryAggregateResultBuckets() { 
  }

  public QueryAggregateResultBuckets buckets(java.util.Map<String, QueryAggregateResultBucketsBucket> buckets) {
    
    this.buckets = buckets;
    return this;
  }

  public QueryAggregateResultBuckets putBucketsItem(String key, QueryAggregateResultBucketsBucket bucketsItem) {
    if (this.buckets == null) {
      this.buckets = new java.util.HashMap<>();
    }
    this.buckets.put(key, bucketsItem);
    return this;
  }

   /**
   * Get buckets
   * @return buckets
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public java.util.Map<String, QueryAggregateResultBucketsBucket> getBuckets() {
    return buckets;
  }


  public void setBuckets(java.util.Map<String, QueryAggregateResultBucketsBucket> buckets) {
    this.buckets = buckets;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryAggregateResultBuckets queryAggregateResultBuckets = (QueryAggregateResultBuckets) o;
    return Objects.equals(this.buckets, queryAggregateResultBuckets.buckets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(buckets);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryAggregateResultBuckets {\n");
    sb.append("    buckets: ").append(toIndentedString(buckets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

