/*
 * Search.io API
 * Search.io offers a search and discovery service with Neuralsearch®, the world's first instant AI search technology. Businesses of all sizes use Search.io to build site search and discovery solutions that maximize e-commerce revenue, optimize on-site customer experience, and scale their online presence.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@search.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sajari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * Redirect contains a target that you can redirect users to if their search query matches a certain condition.
 */
@ApiModel(description = "Redirect contains a target that you can redirect users to if their search query matches a certain condition.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Redirect {
  public static final String SERIALIZED_NAME_COLLECTION_ID = "collection_id";
  @SerializedName(SERIALIZED_NAME_COLLECTION_ID)
  private String collectionId;

  public static final String SERIALIZED_NAME_CONDITION = "condition";
  @SerializedName(SERIALIZED_NAME_CONDITION)
  private String condition;

  public static final String SERIALIZED_NAME_CREATE_TIME = "create_time";
  @SerializedName(SERIALIZED_NAME_CREATE_TIME)
  private OffsetDateTime createTime;

  public static final String SERIALIZED_NAME_DISABLED = "disabled";
  @SerializedName(SERIALIZED_NAME_DISABLED)
  private Boolean disabled;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_TARGET = "target";
  @SerializedName(SERIALIZED_NAME_TARGET)
  private String target;

  public static final String SERIALIZED_NAME_UPDATE_TIME = "update_time";
  @SerializedName(SERIALIZED_NAME_UPDATE_TIME)
  private OffsetDateTime updateTime;

  public Redirect() { 
  }

  
  public Redirect(
     String collectionId, 
     OffsetDateTime createTime, 
     String id, 
     OffsetDateTime updateTime
  ) {
    this();
    this.collectionId = collectionId;
    this.createTime = createTime;
    this.id = id;
    this.updateTime = updateTime;
  }

   /**
   * Output only. The ID of the collection that owns this redirect.
   * @return collectionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Output only. The ID of the collection that owns this redirect.")

  public String getCollectionId() {
    return collectionId;
  }




  public Redirect condition(String condition) {
    
    this.condition = condition;
    return this;
  }

   /**
   * A condition expression applied to a search request that determines whether a search is redirected.  For example, to redirect if the user&#39;s query is &#x60;apples&#x60;, set condition to &#x60;q &#x3D; &#39;apples&#39;&#x60;.
   * @return condition
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "A condition expression applied to a search request that determines whether a search is redirected.  For example, to redirect if the user's query is `apples`, set condition to `q = 'apples'`.")

  public String getCondition() {
    return condition;
  }


  public void setCondition(String condition) {
    this.condition = condition;
  }


   /**
   * Output only. Time the redirect was created.
   * @return createTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Output only. Time the redirect was created.")

  public OffsetDateTime getCreateTime() {
    return createTime;
  }




  public Redirect disabled(Boolean disabled) {
    
    this.disabled = disabled;
    return this;
  }

   /**
   * If disabled, the redirect is never triggered.
   * @return disabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If disabled, the redirect is never triggered.")

  public Boolean getDisabled() {
    return disabled;
  }


  public void setDisabled(Boolean disabled) {
    this.disabled = disabled;
  }


   /**
   * Output only. The redirect&#39;s ID.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Output only. The redirect's ID.")

  public String getId() {
    return id;
  }




  public Redirect target(String target) {
    
    this.target = target;
    return this;
  }

   /**
   * The target to redirect the user to if their query matches &#x60;condition&#x60;.  For searches performed in a browser, target is usually a URL but it can be any value that your integration can interpret as a redirect.  For example, for URLs that you need to resolve at runtime, target might be a URL template string. For apps, target might be a unique identifier used to send the user to the correct view.
   * @return target
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The target to redirect the user to if their query matches `condition`.  For searches performed in a browser, target is usually a URL but it can be any value that your integration can interpret as a redirect.  For example, for URLs that you need to resolve at runtime, target might be a URL template string. For apps, target might be a unique identifier used to send the user to the correct view.")

  public String getTarget() {
    return target;
  }


  public void setTarget(String target) {
    this.target = target;
  }


   /**
   * Output only. Time the redirect was last updated.
   * @return updateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Output only. Time the redirect was last updated.")

  public OffsetDateTime getUpdateTime() {
    return updateTime;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Redirect redirect = (Redirect) o;
    return Objects.equals(this.collectionId, redirect.collectionId) &&
        Objects.equals(this.condition, redirect.condition) &&
        Objects.equals(this.createTime, redirect.createTime) &&
        Objects.equals(this.disabled, redirect.disabled) &&
        Objects.equals(this.id, redirect.id) &&
        Objects.equals(this.target, redirect.target) &&
        Objects.equals(this.updateTime, redirect.updateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(collectionId, condition, createTime, disabled, id, target, updateTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Redirect {\n");
    sb.append("    collectionId: ").append(toIndentedString(collectionId)).append("\n");
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    disabled: ").append(toIndentedString(disabled)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

