/*
 * Sajari API
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sajari.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * UpsertRecordResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UpsertRecordResponse {
    public static final String SERIALIZED_NAME_KEY = "key";
    @SerializedName(SERIALIZED_NAME_KEY)
    private RecordKey key;

    public static final String SERIALIZED_NAME_VARIABLES = "variables";
    @SerializedName(SERIALIZED_NAME_VARIABLES)
    private java.util.Map<String, Object> variables = null;


    public UpsertRecordResponse key(RecordKey key) {

        this.key = key;
        return this;
    }

    /**
     * Get key
     *
     * @return key
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public RecordKey getKey() {
        return key;
    }


    public void setKey(RecordKey key) {
        this.key = key;
    }


    public UpsertRecordResponse variables(java.util.Map<String, Object> variables) {

        this.variables = variables;
        return this;
    }

    public UpsertRecordResponse putVariablesItem(String key, Object variablesItem) {
        if (this.variables == null) {
            this.variables = new java.util.HashMap<>();
        }
        this.variables.put(key, variablesItem);
        return this;
    }

    /**
     * The modified variables returned by the pipeline after it has finished processing.
     *
     * @return variables
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The modified variables returned by the pipeline after it has finished processing.")

    public java.util.Map<String, Object> getVariables() {
        return variables;
    }


    public void setVariables(java.util.Map<String, Object> variables) {
        this.variables = variables;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpsertRecordResponse upsertRecordResponse = (UpsertRecordResponse) o;
        return Objects.equals(this.key, upsertRecordResponse.key) &&
                Objects.equals(this.variables, upsertRecordResponse.variables);
    }

    @Override
    public int hashCode() {
        return Objects.hash(key, variables);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UpsertRecordResponse {\n");
        sb.append("    key: ").append(toIndentedString(key)).append("\n");
        sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

