/*
 * Sajari API
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sajari.client.model;

import org.junit.Test;

/**
 * Model tests for BatchCreateSchemaFieldsResponse
 */
public class BatchCreateSchemaFieldsResponseTest {
    private final BatchCreateSchemaFieldsResponse model = new BatchCreateSchemaFieldsResponse();

    /**
     * Model tests for BatchCreateSchemaFieldsResponse
     */
    @Test
    public void testBatchCreateSchemaFieldsResponse() {
        // TODO: test BatchCreateSchemaFieldsResponse
    }

    /**
     * Test the property 'fields'
     */
    @Test
    public void fieldsTest() {
        // TODO: test fields
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

}
