/*
 * Sajari API
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sajari.client.model;

import org.junit.Test;

/**
 * Model tests for BatchUpsertRecordsResponseKey
 */
public class BatchUpsertRecordsResponseKeyTest {
    private final BatchUpsertRecordsResponseKey model = new BatchUpsertRecordsResponseKey();

    /**
     * Model tests for BatchUpsertRecordsResponseKey
     */
    @Test
    public void testBatchUpsertRecordsResponseKey() {
        // TODO: test BatchUpsertRecordsResponseKey
    }

    /**
     * Test the property 'index'
     */
    @Test
    public void indexTest() {
        // TODO: test index
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

}
