/*
 * Sajari API
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sajari.client.model;

import org.junit.Test;

/**
 * Model tests for ListPipelinesResponse
 */
public class ListPipelinesResponseTest {
    private final ListPipelinesResponse model = new ListPipelinesResponse();

    /**
     * Model tests for ListPipelinesResponse
     */
    @Test
    public void testListPipelinesResponse() {
        // TODO: test ListPipelinesResponse
    }

    /**
     * Test the property 'pipelines'
     */
    @Test
    public void pipelinesTest() {
        // TODO: test pipelines
    }

    /**
     * Test the property 'nextPageToken'
     */
    @Test
    public void nextPageTokenTest() {
        // TODO: test nextPageToken
    }

}
