/*
 * Sajari API
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sajari.client.model;

import org.junit.Test;

/**
 * Model tests for Pipeline
 */
public class PipelineTest {
    private final Pipeline model = new Pipeline();

    /**
     * Model tests for Pipeline
     */
    @Test
    public void testPipeline() {
        // TODO: test Pipeline
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'preSteps'
     */
    @Test
    public void preStepsTest() {
        // TODO: test preSteps
    }

    /**
     * Test the property 'postSteps'
     */
    @Test
    public void postStepsTest() {
        // TODO: test postSteps
    }

    /**
     * Test the property 'collectionDefault'
     */
    @Test
    public void collectionDefaultTest() {
        // TODO: test collectionDefault
    }

    /**
     * Test the property 'defaultVersion'
     */
    @Test
    public void defaultVersionTest() {
        // TODO: test defaultVersion
    }

}
