/*
 * Sajari API
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sajari.client.model;

import org.junit.Test;

/**
 * Model tests for QueryAggregateResultPercentile
 */
public class QueryAggregateResultPercentileTest {
    private final QueryAggregateResultPercentile model = new QueryAggregateResultPercentile();

    /**
     * Model tests for QueryAggregateResultPercentile
     */
    @Test
    public void testQueryAggregateResultPercentile() {
        // TODO: test QueryAggregateResultPercentile
    }

    /**
     * Test the property 'percentiles'
     */
    @Test
    public void percentilesTest() {
        // TODO: test percentiles
    }

    /**
     * Test the property 'cdf'
     */
    @Test
    public void cdfTest() {
        // TODO: test cdf
    }

}
