/*
 * Sajari API
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sajari.client.model;

import org.junit.Test;

/**
 * Model tests for QueryResultToken
 */
public class QueryResultTokenTest {
    private final QueryResultToken model = new QueryResultToken();

    /**
     * Model tests for QueryResultToken
     */
    @Test
    public void testQueryResultToken() {
        // TODO: test QueryResultToken
    }

    /**
     * Test the property 'click'
     */
    @Test
    public void clickTest() {
        // TODO: test click
    }

    /**
     * Test the property 'posNeg'
     */
    @Test
    public void posNegTest() {
        // TODO: test posNeg
    }

}
