/*
 * Sajari API
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sajari.client.model;

import org.junit.Test;

/**
 * Model tests for QueryAggregateResultDate
 */
public class QueryAggregateResultDateTest {
    private final QueryAggregateResultDate model = new QueryAggregateResultDate();

    /**
     * Model tests for QueryAggregateResultDate
     */
    @Test
    public void testQueryAggregateResultDate() {
        // TODO: test QueryAggregateResultDate
    }

    /**
     * Test the property 'dates'
     */
    @Test
    public void datesTest() {
        // TODO: test dates
    }

}
