/*
 * Sajari API
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sajari.client.model;

import org.junit.Test;

/**
 * Model tests for SetDefaultPipelineRequest
 */
public class SetDefaultPipelineRequestTest {
    private final SetDefaultPipelineRequest model = new SetDefaultPipelineRequest();

    /**
     * Model tests for SetDefaultPipelineRequest
     */
    @Test
    public void testSetDefaultPipelineRequest() {
        // TODO: test SetDefaultPipelineRequest
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'pipeline'
     */
    @Test
    public void pipelineTest() {
        // TODO: test pipeline
    }

}
