/*
 * Sajari API
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sajari.client.model;

import org.junit.Test;

/**
 * Model tests for UpsertRecordRequestPipeline
 */
public class UpsertRecordRequestPipelineTest {
    private final UpsertRecordRequestPipeline model = new UpsertRecordRequestPipeline();

    /**
     * Model tests for UpsertRecordRequestPipeline
     */
    @Test
    public void testUpsertRecordRequestPipeline() {
        // TODO: test UpsertRecordRequestPipeline
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

}
